// Code generated by girgen. DO NOT EDIT.

package gdkx11

import (
	"unsafe"

	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gdk/v3"
)

// #cgo pkg-config: gdk-x11-3.0 gtk+-3.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <gdk/gdkx.h>
// #include <glib-object.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.gdk_x11_visual_get_type()), F: marshalX11Visualer},
	})
}

type X11Visual struct {
	_ [0]func() // equal guard
	gdk.Visual
}

var (
	_ externglib.Objector = (*X11Visual)(nil)
)

func wrapX11Visual(obj *externglib.Object) *X11Visual {
	return &X11Visual{
		Visual: gdk.Visual{
			Object: obj,
		},
	}
}

func marshalX11Visualer(p uintptr) (interface{}, error) {
	return wrapX11Visual(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}
