// Code generated by girgen. DO NOT EDIT.

package gtk

import (
	externglib "github.com/gotk3/gotk3/glib"
)

// #cgo pkg-config:
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <glib-object.h>
// #include <gtk/gtk.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.gtk_gesture_zoom_get_type()), F: marshalGestureZoom},
	})
}

// GestureZoom: `GtkGestureZoom` is a `GtkGesture` for 2-finger pinch/zoom
// gestures.
//
// Whenever the distance between both tracked sequences changes, the
// [signal@Gtk.GestureZoom::scale-changed] signal is emitted to report the scale
// factor.
type GestureZoom interface {
	Gesture

	// ScaleDelta gets the scale delta.
	//
	// If @gesture is active, this function returns the zooming difference since
	// the gesture was recognized (hence the starting point is considered 1:1).
	// If @gesture is not active, 1 is returned.
	ScaleDelta() float64
}

// gestureZoom implements the GestureZoom interface.
type gestureZoom struct {
	Gesture
}

var _ GestureZoom = (*gestureZoom)(nil)

// WrapGestureZoom wraps a GObject to the right type. It is
// primarily used internally.
func WrapGestureZoom(obj *externglib.Object) GestureZoom {
	return GestureZoom{
		Gesture: WrapGesture(obj),
	}
}

func marshalGestureZoom(p uintptr) (interface{}, error) {
	val := C.g_value_get_object((*C.GValue)(unsafe.Pointer(p)))
	obj := externglib.Take(unsafe.Pointer(val))
	return WrapGestureZoom(obj), nil
}

// ScaleDelta gets the scale delta.
//
// If @gesture is active, this function returns the zooming difference since
// the gesture was recognized (hence the starting point is considered 1:1).
// If @gesture is not active, 1 is returned.
func (g gestureZoom) ScaleDelta() float64 {
	var _arg0 *C.GtkGestureZoom

	_arg0 = (*C.GtkGestureZoom)(unsafe.Pointer(g.Native()))

	var _cret C.double

	_cret = C.gtk_gesture_zoom_get_scale_delta(_arg0)

	var _gdouble float64

	_gdouble = (float64)(_cret)

	return _gdouble
}
