// Code generated by girgen. DO NOT EDIT.

package gtk

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	externglib "github.com/gotk3/gotk3/glib"
)

// #cgo pkg-config: gtk4
// #cgo CFLAGS: -Wno-deprecated-declarations
//
// #include <glib-object.h>
// #include <gtk/gtk.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.gtk_string_filter_match_mode_get_type()), F: marshalStringFilterMatchMode},
		{T: externglib.Type(C.gtk_string_filter_get_type()), F: marshalStringFilter},
	})
}

// StringFilterMatchMode specifies how search strings are matched inside text.
type StringFilterMatchMode int

const (
	// Exact: the search string and text must match exactly.
	StringFilterMatchModeExact StringFilterMatchMode = iota
	// Substring: the search string must be contained as a substring inside the
	// text.
	StringFilterMatchModeSubstring
	// Prefix: the text must begin with the search string.
	StringFilterMatchModePrefix
)

func marshalStringFilterMatchMode(p uintptr) (interface{}, error) {
	return StringFilterMatchMode(C.g_value_get_enum((*C.GValue)(unsafe.Pointer(p)))), nil
}

// StringFilter: `GtkStringFilter` determines whether to include items by
// comparing strings to a fixed search term.
//
// The strings are obtained from the items by evaluating a `GtkExpression` set
// with [method@Gtk.StringFilter.set_expression], and they are compared against
// a search term set with [method@Gtk.StringFilter.set_search].
//
// `GtkStringFilter` has several different modes of comparison - it can match
// the whole string, just a prefix, or any substring. Use
// [method@Gtk.StringFilter.set_match_mode] choose a mode.
//
// It is also possible to make case-insensitive comparisons, with
// [method@Gtk.StringFilter.set_ignore_case].
type StringFilter interface {
	Filter

	// AsFilter casts the class to the Filter interface.
	AsFilter() Filter

	// Changed emits the Filter::changed signal to notify all users of the
	// filter that the filter changed. Users of the filter should then check
	// items again via gtk_filter_match().
	//
	// Depending on the @change parameter, not all items need to be changed, but
	// only some. Refer to the FilterChange documentation for details.
	//
	// This function is intended for implementors of Filter subclasses and
	// should not be called from other functions.
	//
	// This method is inherited from Filter
	Changed(change FilterChange)
	// GetStrictness gets the known strictness of @filters. If the strictness is
	// not known, GTK_FILTER_MATCH_SOME is returned.
	//
	// This value may change after emission of the Filter::changed signal.
	//
	// This function is meant purely for optimization purposes, filters can
	// choose to omit implementing it, but FilterListModel uses it.
	//
	// This method is inherited from Filter
	GetStrictness() FilterMatch
	// Match checks if the given @item is matched by the filter or not.
	//
	// This method is inherited from Filter
	Match(item gextras.Objector) bool

	// Expression gets the expression that the string filter uses to obtain
	// strings from items.
	Expression() Expression
	// IgnoreCase returns whether the filter ignores case differences.
	IgnoreCase() bool
	// MatchMode returns the match mode that the filter is using.
	MatchMode() StringFilterMatchMode
	// Search gets the search term.
	Search() string
	// SetExpression sets the expression that the string filter uses to obtain
	// strings from items.
	//
	// The expression must have a value type of G_TYPE_STRING.
	SetExpression(expression Expression)
	// SetIgnoreCase sets whether the filter ignores case differences.
	SetIgnoreCase(ignoreCase bool)
	// SetMatchMode sets the match mode for the filter.
	SetMatchMode(mode StringFilterMatchMode)
	// SetSearch sets the string to search for.
	SetSearch(search string)
}

// stringFilter implements the StringFilter interface.
type stringFilter struct {
	*externglib.Object
}

var _ StringFilter = (*stringFilter)(nil)

// WrapStringFilter wraps a GObject to a type that implements
// interface StringFilter. It is primarily used internally.
func WrapStringFilter(obj *externglib.Object) StringFilter {
	return stringFilter{obj}
}

func marshalStringFilter(p uintptr) (interface{}, error) {
	val := C.g_value_get_object((*C.GValue)(unsafe.Pointer(p)))
	obj := externglib.Take(unsafe.Pointer(val))
	return WrapStringFilter(obj), nil
}

// NewStringFilter creates a new string filter.
//
// You will want to set up the filter by providing a string to search for and by
// providing a property to look up on the item.
func NewStringFilter(expression Expression) StringFilter {
	var _arg1 *C.GtkExpression   // out
	var _cret *C.GtkStringFilter // in

	_arg1 = (*C.GtkExpression)(unsafe.Pointer(expression.Native()))

	_cret = C.gtk_string_filter_new(_arg1)

	var _stringFilter StringFilter // out

	_stringFilter = gextras.CastObject(externglib.AssumeOwnership(unsafe.Pointer(_cret))).(StringFilter)

	return _stringFilter
}

func (s stringFilter) AsFilter() Filter {
	return WrapFilter(gextras.InternObject(s))
}

func (s stringFilter) Changed(change FilterChange) {
	WrapFilter(gextras.InternObject(s)).Changed(change)
}

func (s stringFilter) GetStrictness() FilterMatch {
	return WrapFilter(gextras.InternObject(s)).GetStrictness()
}

func (s stringFilter) Match(item gextras.Objector) bool {
	return WrapFilter(gextras.InternObject(s)).Match(item)
}

func (s stringFilter) Expression() Expression {
	var _arg0 *C.GtkStringFilter // out
	var _cret *C.GtkExpression   // in

	_arg0 = (*C.GtkStringFilter)(unsafe.Pointer(s.Native()))

	_cret = C.gtk_string_filter_get_expression(_arg0)

	var _expression Expression // out

	_expression = gextras.CastObject(externglib.Take(unsafe.Pointer(_cret))).(Expression)

	return _expression
}

func (s stringFilter) IgnoreCase() bool {
	var _arg0 *C.GtkStringFilter // out
	var _cret C.gboolean         // in

	_arg0 = (*C.GtkStringFilter)(unsafe.Pointer(s.Native()))

	_cret = C.gtk_string_filter_get_ignore_case(_arg0)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

func (s stringFilter) MatchMode() StringFilterMatchMode {
	var _arg0 *C.GtkStringFilter         // out
	var _cret C.GtkStringFilterMatchMode // in

	_arg0 = (*C.GtkStringFilter)(unsafe.Pointer(s.Native()))

	_cret = C.gtk_string_filter_get_match_mode(_arg0)

	var _stringFilterMatchMode StringFilterMatchMode // out

	_stringFilterMatchMode = StringFilterMatchMode(_cret)

	return _stringFilterMatchMode
}

func (s stringFilter) Search() string {
	var _arg0 *C.GtkStringFilter // out
	var _cret *C.char            // in

	_arg0 = (*C.GtkStringFilter)(unsafe.Pointer(s.Native()))

	_cret = C.gtk_string_filter_get_search(_arg0)

	var _utf8 string // out

	_utf8 = C.GoString(_cret)

	return _utf8
}

func (s stringFilter) SetExpression(expression Expression) {
	var _arg0 *C.GtkStringFilter // out
	var _arg1 *C.GtkExpression   // out

	_arg0 = (*C.GtkStringFilter)(unsafe.Pointer(s.Native()))
	_arg1 = (*C.GtkExpression)(unsafe.Pointer(expression.Native()))

	C.gtk_string_filter_set_expression(_arg0, _arg1)
}

func (s stringFilter) SetIgnoreCase(ignoreCase bool) {
	var _arg0 *C.GtkStringFilter // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.GtkStringFilter)(unsafe.Pointer(s.Native()))
	if ignoreCase {
		_arg1 = C.TRUE
	}

	C.gtk_string_filter_set_ignore_case(_arg0, _arg1)
}

func (s stringFilter) SetMatchMode(mode StringFilterMatchMode) {
	var _arg0 *C.GtkStringFilter         // out
	var _arg1 C.GtkStringFilterMatchMode // out

	_arg0 = (*C.GtkStringFilter)(unsafe.Pointer(s.Native()))
	_arg1 = C.GtkStringFilterMatchMode(mode)

	C.gtk_string_filter_set_match_mode(_arg0, _arg1)
}

func (s stringFilter) SetSearch(search string) {
	var _arg0 *C.GtkStringFilter // out
	var _arg1 *C.char            // out

	_arg0 = (*C.GtkStringFilter)(unsafe.Pointer(s.Native()))
	_arg1 = (*C.char)(C.CString(search))
	defer C.free(unsafe.Pointer(_arg1))

	C.gtk_string_filter_set_search(_arg0, _arg1)
}
