// Code generated by girgen. DO NOT EDIT.

package gtk

import (
	"unsafe"
)

// #cgo pkg-config: gtk+-3.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <glib-object.h>
// #include <gtk/gtk-a11y.h>
// #include <gtk/gtk.h>
// #include <gtk/gtkx.h>
import "C"

type LabelPrivate struct {
	native C.GtkLabelPrivate
}

// WrapLabelPrivate wraps the C unsafe.Pointer to be the right type. It is
// primarily used internally.
func WrapLabelPrivate(ptr unsafe.Pointer) *LabelPrivate {
	if ptr == nil {
		return nil
	}

	return (*LabelPrivate)(ptr)
}

func marshalLabelPrivate(p uintptr) (interface{}, error) {
	b := C.g_value_get_boxed((*C.GValue)(unsafe.Pointer(p)))
	return WrapLabelPrivate(unsafe.Pointer(b)), nil
}

// Native returns the underlying C source pointer.
func (l *LabelPrivate) Native() unsafe.Pointer {
	return unsafe.Pointer(&l.native)
}

type LabelSelectionInfo struct {
	native C.GtkLabelSelectionInfo
}

// WrapLabelSelectionInfo wraps the C unsafe.Pointer to be the right type. It is
// primarily used internally.
func WrapLabelSelectionInfo(ptr unsafe.Pointer) *LabelSelectionInfo {
	if ptr == nil {
		return nil
	}

	return (*LabelSelectionInfo)(ptr)
}

func marshalLabelSelectionInfo(p uintptr) (interface{}, error) {
	b := C.g_value_get_boxed((*C.GValue)(unsafe.Pointer(p)))
	return WrapLabelSelectionInfo(unsafe.Pointer(b)), nil
}

// Native returns the underlying C source pointer.
func (l *LabelSelectionInfo) Native() unsafe.Pointer {
	return unsafe.Pointer(&l.native)
}
